class LanguageResources:
    """多语言资源类"""
    
    @classmethod
    def get_languages(cls):
        """獲取所有語言資源"""
        return {
            "zh_tw": cls.zh_tw,
            "en": cls.en,
            "zh_cn": cls.zh_cn
        }
    
    # 繁體中文
    zh_tw = {
        "window_title": "iperf3 GUI",
        "mode": "模式",
        "client": "客戶端",
        "server": "伺服器",
        "parameters": "參數",
        "host": "主機:",
        "port": "埠:",
        "test_time": "測試時間(秒):",
        "bandwidth_limit": "頻寬限制:",
        "parallel_connections": "並行連接數:",
        "report_interval": "報告間隔(秒):",
        "udp_mode": "UDP模式:",
        "reverse_test": "反向測試:",
        "output_format": "輸出格式:",
        "extra_params": "額外參數:",
        "normal": "普通",
        "start_test": "開始測試",
        "stop_test": "停止測試",
        "clear_results": "清除結果",
        "save_results": "保存結果",
        "test_graph": "測試圖表",
        "test_graph_message": "這是使用模擬數據的圖表測試。",
        "test_graph_explanation": "顯示的數據不是來自實際的 iperf 測試。",
        "test_graph_status": "圖表測試模式 - 模擬數據",
        "control": "控制",
        "output": "輸出",
        "graph": "圖表",
        "ready": "就緒",
        "test_running": "測試運行中...",
        "test_stopped": "測試已停止",
        "test_completed": "測試完成",
        "results_cleared": "結果已清除",
        "results_saved": "結果已保存",
        "save_text_results": "保存文本結果",
        "save_graph": "保存圖表",
        "text_file": "文本文件 (*.txt)",
        "png_image": "PNG圖片 (*.png)",
        "warning": "警告",
        "error": "錯誤",
        "iperf3_not_found": "未檢測到iperf3。請確保已安裝iperf3並添加到系統路徑中。",
        "network_throughput": "網絡吞吐量",
        "bandwidth": "頻寬",
        "time": "時間",
        # Ping相關翻譯
        "ping": "Ping",
        "start_ping": "開始 Ping",
        "stop_ping": "停止 Ping",
        "ping_graph": "Ping 圖表",
        "no_host": "請輸入要 ping 的主機",
        "ping_latency": "Ping 延遲",
        "latency": "延遲",
        # 新增的翻譯
        "bidirectional": "雙向測試",
        "bidirectional_tooltip": "同時測試上傳和下載速度",
        "bandwidth_sent": "上傳速度",
        "bandwidth_received": "下載速度",
        # 圖表統計信息
        "average": "平均",
        "maximum": "最大",
        "minimum": "最小",
        "upload_average": "上傳平均",
        "download_average": "下載平均",
        "bandwidth_graph": "網絡頻寬圖表",
        "test_data_generated": "測試數據已生成"
    }
    
    # English
    en = {
        "window_title": "iperf3 GUI",
        "mode": "Mode",
        "client": "Client",
        "server": "Server",
        "parameters": "Parameters",
        "host": "Host:",
        "port": "Port:",
        "test_time": "Test Time (sec):",
        "bandwidth_limit": "Bandwidth Limit:",
        "parallel_connections": "Parallel Connections:",
        "report_interval": "Report Interval (sec):",
        "udp_mode": "UDP Mode:",
        "reverse_test": "Reverse Test:",
        "output_format": "Output Format:",
        "extra_params": "Extra Parameters:",
        "normal": "Normal",
        "start_test": "Start Test",
        "stop_test": "Stop Test",
        "clear_results": "Clear Results",
        "save_results": "Save Results",
        "test_graph": "Test Graph",
        "test_graph_message": "This is a graph test with simulated data.",
        "test_graph_explanation": "The data shown is not from an actual iperf test.",
        "test_graph_status": "Graph test mode - simulated data",
        "control": "Control",
        "output": "Output",
        "graph": "Graph",
        "ready": "Ready",
        "test_running": "Test running...",
        "test_stopped": "Test stopped",
        "test_completed": "Test completed",
        "results_cleared": "Results cleared",
        "results_saved": "Results saved",
        "save_text_results": "Save Text Results",
        "save_graph": "Save Graph",
        "text_file": "Text Files (*.txt)",
        "png_image": "PNG Images (*.png)",
        "warning": "Warning",
        "error": "Error",
        "iperf3_not_found": "iperf3 not found. Please make sure iperf3 is installed and added to your system path.",
        "network_throughput": "Network Throughput",
        "bandwidth": "Bandwidth",
        "time": "Time",
        # Ping related translations
        "ping": "Ping",
        "start_ping": "Start Ping",
        "stop_ping": "Stop Ping",
        "ping_graph": "Ping Graph",
        "no_host": "Please enter a host to ping",
        "ping_latency": "Ping Latency",
        "latency": "Latency",
        # New translations
        "bidirectional": "Bidirectional Test",
        "bidirectional_tooltip": "Test both upload and download speeds simultaneously",
        "bandwidth_sent": "Upload Speed",
        "bandwidth_received": "Download Speed",
        # Graph statistics
        "average": "Average",
        "maximum": "Maximum",
        "minimum": "Minimum",
        "upload_average": "Upload Average",
        "download_average": "Download Average",
        "bandwidth_graph": "Bandwidth Graph",
        "test_data_generated": "Test data generated"
    }
    
    # 简体中文
    zh_cn = {
        "window_title": "iperf3 GUI",
        "mode": "模式",
        "client": "客户端",
        "server": "服务器",
        "parameters": "参数",
        "host": "主机:",
        "port": "端口:",
        "test_time": "测试时间(秒):",
        "bandwidth_limit": "带宽限制:",
        "parallel_connections": "并行连接数:",
        "report_interval": "报告间隔(秒):",
        "udp_mode": "UDP模式:",
        "reverse_test": "反向测试:",
        "output_format": "输出格式:",
        "extra_params": "额外参数:",
        "normal": "普通",
        "start_test": "开始测试",
        "stop_test": "停止测试",
        "clear_results": "清除结果",
        "save_results": "保存结果",
        "test_graph": "测试图表",
        "test_graph_message": "这是使用模拟数据的图表测试。",
        "test_graph_explanation": "显示的数据不是来自实际的 iperf 测试。",
        "test_graph_status": "图表测试模式 - 模拟数据",
        "control": "控制",
        "output": "输出",
        "graph": "图表",
        "ready": "就绪",
        "test_running": "测试运行中...",
        "test_stopped": "测试已停止",
        "test_completed": "测试完成",
        "results_cleared": "结果已清除",
        "results_saved": "结果已保存",
        "save_text_results": "保存文本结果",
        "save_graph": "保存图表",
        "text_file": "文本文件 (*.txt)",
        "png_image": "PNG图片 (*.png)",
        "warning": "警告",
        "error": "错误",
        "iperf3_not_found": "未检测到iperf3。请确保已安装iperf3并添加到系统路径中。",
        "network_throughput": "网络吞吐量",
        "bandwidth": "带宽",
        "time": "时间",
        # Ping相关翻译
        "ping": "Ping",
        "start_ping": "开始 Ping",
        "stop_ping": "停止 Ping",
        "ping_graph": "Ping 图表",
        "no_host": "请输入要 ping 的主机",
        "ping_latency": "Ping 延迟",
        "latency": "延迟",
        # 新增的翻译
        "bidirectional": "双向测试",
        "bidirectional_tooltip": "同时测试上传和下载速度",
        "bandwidth_sent": "上传速度",
        "bandwidth_received": "下载速度",
        # 图表统计信息
        "average": "平均",
        "maximum": "最大",
        "minimum": "最小",
        "upload_average": "上传平均",
        "download_average": "下载平均",
        "bandwidth_graph": "网络带宽图表",
        "test_data_generated": "测试数据已生成"
    }